### PR TITLE
Adopt Model Server API v2

### LINKED ISSUE #23: Adopt Model Server API v2
Pursuant to [API v2 support in the Theia _Model Server_  services](/eclipse-emfcloud/emfcloud-modelserver-theia/issues/88), it would be nice to adopt the V2 client in the Model-Server-aware property view also, so that it may connect to the [Node.js façade for the _Model Server_][msnode] in a Theia application.

[msnode]: /eclipse-emfcloud/modelserver-node/

### PR DESCRIPTION
**Pull request by cdamus**
_**Note** that this change depends on new APIs in eclipse-emfcloud/emfcloud-modelserver-theia#92 and so cannot be merged before that PR is merged and a build of it published._

- inject the API V2 variants of the Theia model-server client and subscription service
- handle the API V2 variant of the incremental update notification with JSON Patches to trigger UI updates

Fixes #23.

Contributed on behalf of STMicroelectronics.

### CODE REVIEW

**Review by ndoschek — CHANGES_REQUESTED** [review]
Thanks @cdamus, changes look overall good to me!
Could you please have another look at the currently failing build? Thanks!

```
stdout: 'yarn run v1.22.18\n' +
    '$ yarn run clean && yarn run build\n' +
    '$ rimraf lib\n' +
    '$ tsc && yarn run lint\n' +
    `src/browser/modelserver-property-data-service.ts(12,10): error TS2724: Module '"../../../node_modules/@eclipse-emfcloud/modelserver-theia/lib/common"' has no exported member 'TheiaModelServerClientV2'. Did you mean 'TheiaModelServerClient'?\n` +
    `src/browser/modelserver-widget-provider.ts(12,10): error TS2724: Module '"../../../node_modules/@eclipse-emfcloud/modelserver-client/lib"' has no exported member 'IncrementalUpdateNotificationV2'. Did you mean 'IncrementalUpdateNotification'?\n` +
    `src/browser/modelserver-widget-provider.ts(12,43): error TS2305: Module '"../../../node_modules/@eclipse-emfcloud/modelserver-client/lib"' has no exported member 'Operations'.\n` +
    `src/browser/modelserver-widget-provider.ts(13,10): error TS2724: Module '"../../../node_modules/@eclipse-emfcloud/modelserver-theia/lib/common"' has no exported member 'TheiaModelServerClientV2'. Did you mean 'TheiaModelServerClient'?\n` +
    `src/browser/modelserver-widget-provider.ts(14,10): error TS2724: Module '"../../../node_modules/@eclipse-emfcloud/modelserver-theia/lib/browser"' has no exported member 'ModelServerSubscriptionServiceV2'. Did you mean 'ModelServerSubscriptionService'?\n` +
    "src/browser/modelserver-widget-provider.ts(43,64): error TS7006: Parameter 'incrementalUpdate' implicitly has an 'any' type.\n" +
...
```

**Comment by cdamus** [comment]
Hi @ndoschek thanks for the review. The build is expected to fail until PR eclipse-emfcloud/emfcloud-modelserver-theia#92 is merged and publishes a build because that provides new API required here. The dependency note in my description didn't make that clear, sorry.

**Comment by ndoschek** [comment]
> Hi @ndoschek thanks for the review. The build is expected to fail until PR [eclipse-emfcloud/emfcloud-modelserver-theia#92](https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/pull/92) is merged and publishes a build because that provides new API required here. The dependency note in my description didn't make that clear, sorry.

Ah that totally makes sense, sorry for not keeping that in mind :sweat_smile:!

**Comment by cdamus** [comment]
@ndoschek Commit 6552a97e5b3811f6d5d644fe9569499921387f9d rebuilds the lock file to pick up the latest `modelserver-theia` and should now build.

**Review by ndoschek — APPROVED** [review]
Great, thanks a lot @cdamus! Looks great to me! :taco:

**Pull request merged**
